// SPDX-License-Identifier: Apache-2.0
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const definitions=[['Artwork','oes/v1/artwork.schema.json','artwork'],['Exhibition','oes/v1/exhibition.schema.json','exhibition'],['Lifecycle','oes/v1/lifecycle.schema.json','lifecycle'],['OexManifest','oex/v1/manifest.schema.json','oex'],['OedDeployment','oed/v1/deployment.schema.json','oed']];
const schemas=await Promise.all(definitions.map(async([name,path,alias])=>({name,path,alias,text:await readFile(new URL('../'+path,import.meta.url),'utf8')})));
for(const entry of schemas)entry.schema=JSON.parse(entry.text);
// Deliberately limited to current schema vocabulary. Unknown structural keywords fail
// generation rather than silently widening a future schema's types.
const allowed=new Set(['$schema','$id','$defs','$ref','title','description','type','properties','required','additionalProperties','propertyNames','maxProperties','items','minItems','maxItems','const','enum','anyOf','oneOf','minimum','maximum','exclusiveMinimum','format','pattern','minLength','maxLength']);
function type(s,owner) {
 if(typeof s==='boolean')return s?'JsonValue':'never';
 for(const key of Object.keys(s))if(!allowed.has(key))throw new Error('Unsupported schema keyword '+key);
 if(s.$ref){const [id,pointer='']=s.$ref.split('#');const target=id?schemas.find(e=>e.schema.$id===id):owner;if(!target)throw new Error('Unresolved schema '+id);const resolved=pointer?pointer.slice(1).split('/').reduce((obj,k)=>obj[k.replace(/~1/g,'/').replace(/~0/g,'~')],target.schema):target.schema;if(!resolved)throw new Error('Unresolved pointer');return type(resolved,target);}
 let base;
 if('const'in s)base=JSON.stringify(s.const);
 else if(s.enum)base=s.enum.map(v=>JSON.stringify(v)).join(' | ');
 else if(s.type==='object'){
 const required=new Set(s.required||[]);const fields=Object.entries(s.properties||{}).map(([k,v])=>JSON.stringify(k)+(required.has(k)?'':'?')+': '+type(v,owner)+';');
 if(s.additionalProperties!==false)fields.push('[key: string]: '+(s.additionalProperties&&typeof s.additionalProperties==='object'?type(s.additionalProperties,owner):'JsonValue')+';');base='{ '+fields.join(' ')+' }';
 } else if(s.type==='array'){const item=type(s.items??true,owner);base=s.minItems===s.maxItems&&Number.isInteger(s.maxItems)&&s.maxItems<=16?'['+Array(s.maxItems).fill(item).join(', ')+']':'Array<'+item+'>';}
 else if(s.type==='string'||s.type==='boolean')base=s.type;
 else if(s.type==='number'||s.type==='integer')base='number';
 else if(s.type==='null')base='null';
 else if(s.type)throw new Error('Unsupported type '+s.type);
 const union=s.oneOf||s.anyOf;
 // anyOf with required-only branches has no additional structural representation.
 const structural=union?.every(v=>Object.keys(v).some(k=>['$ref','type','const','enum','properties','oneOf','anyOf'].includes(k)));
 if(structural){const u='('+union.map(v=>type(v,owner)).join(' | ')+')';base=base?'('+base+' & '+u+')':u;}
 return base||'JsonValue';
}
let output='// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/generate-types.mjs; do not edit. Runtime validation remains required.\nexport type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n';
for(const entry of schemas){output+='// '+entry.schema.$id+' SHA256 '+createHash('sha256').update(entry.text).digest('hex')+'\nexport type '+entry.name+' = '+type(entry.schema,entry)+';\n';}
output+=await readFile(new URL('../conformance/api-types.txt',import.meta.url),'utf8');
const check=process.argv.includes('--check');
for(const [path,text]of [['types/index.d.ts',output],...schemas.map(e=>['schemas/'+e.alias+'.json',e.text])]){
 const url=new URL('../'+path,import.meta.url);
 if(check){if(await readFile(url,'utf8')!==text)throw new Error('Stale generated artifact '+path);}
 else{await mkdir(new URL('.',url),{recursive:true});await writeFile(url,text);}
}
